name: Trigger internal azimuth-cli test build

on:
  workflow_dispatch:

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Internal test build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: tloncorp/ylem
          event-type: test-breach-docker-ship
