name: Trigger internal azimuth-cli test build

on:
  workflow_dispatch:

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Internal test build
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'tloncorp',
              repo: 'ylem',
              event_type: 'test-breach-ship-docker',
              client_payload: { branch: 'main' }
            });
