name: Trigger internal azimuth-cli prod build

on:
  workflow_dispatch:
  push:
    branches:
      - solaris

jobs:
  trigger-test:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Internal prod build
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'tloncorp',
              repo: 'ylem',
              event_type: 'prod-breach-ship-docker',
              client_payload: { branch: 'main' }
            });
