name: Trigger internal azimuth-cli prod build

on:
  workflow_dispatch:
  push:
    branches:
      - solaris

jobs:
  trigger-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to ylem (prod)
        uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_TOKEN } = process.env;
            await github.repos.createDispatchEvent({
              owner: 'tloncorp',
              repo: 'ylem',
              event_type: 'prod-breach-ship-docker',
              client_payload: { branch: 'main' }
            });
